# CMSC 320 Final Project 
Diego Ferreira, Lillian Mueller, Ananya Uniyal

Intro / overview of tutorial
EDIT THIS SECTION AS PARAGRAPHS LATER
- analyze crime trends between counties (which county is the safest/least safe), most common types of crimes in each county, how much each county spends per student, household in come of each county 
    - look at these trends separately 
    - then look at trends between different factors 
- to determine if wealth can be a predictor of crime rates 
    - wealth defined in two ways: 
        - spending per student in each county
        - median household income 
- based on the data we found online we will only be looking at the years 2017, 2018, 2019

DATA INFO

do years 2019, 2018, and 2017

In [19]:
# PUT ALL PACKAGES HERE
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

# Step 1: Data Collection/Curation and Parsing

Step one focuses on collecting data from various sites. Here we will be reading in csv files from different databases as well as scraping some websites for data. 

The first step here is to download the csv from the Maryland's Open Data Portal (https://opendata.maryland.gov/Public-Safety/Violent-Crime-Property-Crime-by-County-1975-to-Pre/jwfa-fdxs). This dataset contains the violent and property crimes commited in Maryland by county in the years 1975 to Present (unfortunately the data is only availbe up to 2019). Crime is divided into different categories:

1. Murder
2. Rape
3. Robbery
4. Aggrevated Assult
5. Breaking and Entering
6. Larceny Theft
7. Motorvechile theft

The populaiton of each county is also given for each year. We will be looking at crime rates per capita to generalize crime rates over all counties.

DESCRIBE THE CODE BELOW IN DETAIL & INCLDUE LINKS TO WEBSITES TO LEARN MORE LIKE THE CP CRIMES EXAMPLE?
RUBRIC SAYS TO INCLUDE "Links to external documentation and resources that would be useful in
understanding the approach." 

Process of creating the crime_df 
1. Download CSV from https://opendata.maryland.gov/Public-Safety/Violent-Crime-Property-Crime-by-County-1975-to-Pre/jwfa-fdxs and upload this CSV file into github so it can be publicly accessed. 
2. 
- extract data and put into dataframe

In [20]:
# CRIME DATA
# read csv file uploaded on github
crime_data = pd.read_csv("https://raw.githubusercontent.com/lgmueller/lgmueller.github.io/main/Violent_Crime___Property_Crime_by_County__1975_to_Present%20(2).csv")

# contains raw data
crime_data.head()

,JURISDICTION,YEAR,POPULATION,MURDER,RAPE,ROBBERY,AGG. ASSAULT,B & E,LARCENY THEFT,M/V THEFT,...,"B & E PER 100,000 PEOPLE","LARCENY THEFT PER 100,000 PEOPLE","M/V THEFT PER 100,000 PEOPLE","MURDER RATE PERCENT CHANGE PER 100,000 PEOPLE","RAPE RATE PERCENT CHANGE PER 100,000 PEOPLE","ROBBERY RATE PERCENT CHANGE PER 100,000 PEOPLE","AGG. ASSAULT RATE PERCENT CHANGE PER 100,000 PEOPLE","B & E RATE PERCENT CHANGE PER 100,000 PEOPLE","LARCENY THEFT RATE PERCENT CHANGE PER 100,000 PEOPLE","M/V THEFT RATE PERCENT CHANGE PER 100,000 PEOPLE"
0,Allegany County,1975,79655,3,5,20,114,669,1425,93,...,839.9,1789.0,116.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Allegany County,1976,83923,2,2,24,59,581,1384,73,...,692.3,1649.1,87.0,-36.7,-62.0,13.9,-50.9,-17.6,-7.8,-25.5
2,Allegany County,1977,82102,3,7,32,85,592,1390,102,...,721.1,1693.0,124.2,53.3,257.8,36.3,47.3,4.2,2.7,42.8
3,Allegany County,1978,79966,1,2,18,81,539,1390,100,...,674.0,1738.2,125.1,-65.8,-70.7,-42.2,-2.2,-6.5,2.7,0.7
4,Allegany County,1979,79721,1,7,18,84,502,1611,99,...,629.7,2020.8,124.2,0.3,251.1,0.3,4.0,-6.6,16.3,-0.7

Downloaded CSV from https://opendata.maryland.gov/Demographic/Maryland-Median-Household-Income-By-Year-With-Marg/bvk4-qsxs

In [21]:
# MEDIAN HOUSEHOLD INCOME DATA

# Read CSV for median household income 
income_data = pd.read_csv("https://raw.githubusercontent.com/lgmueller/lgmueller.github.io/main/Maryland_Median_Household_Income_By_Year_With_Margin_Of_Error__2010-2019%20(1).csv")
income_data.head()

,Date created,Year,Data,MARYLAND,Allegany County,Anne Arundel County,Baltimore City,Baltimore County,Calvert County,Caroline County,...,Kent County,Montgomery County,Prince George's County,Queen Anne's County,Somerset County,St. Mary's County,Talbot County,Washington County,Wicomico County,Worcester County
0,"September 29, 2020",2010,Income,68933,37083,80908,38186,62300,86536,55480,...,49017,88559,69524,78503,38134,81559,56806,51610,47702,55492
1,"September 29, 2020",2010,MOE,833,2826,2311,1414,2006,5064,2965,...,4582,2710,1609,5181,2747,5070,3948,3327,3097,3507
2,"September 29, 2020",2011,Income,70075,38504,82980,38478,62309,88406,50809,...,49795,92288,70114,75158,35426,80943,55145,52028,45788,48472
3,"September 29, 2020",2011,MOE,760,2693,3430,1536,1728,4369,4213,...,4603,2758,1911,6363,3426,2717,4929,2928,3582,4653
4,"September 29, 2020",2012,Income,71169,38670,87083,39077,62413,87215,48772,...,49969,94365,69258,79012,34454,85478,61529,52604,50204,55875

DESCRIBE CODE AND DATA
Links
https://conduitstreet.mdcounties.org/2018/02/21/chart-compares-school-funding-per-student-county-by-county/
https://conduitstreet.mdcounties.org/2019/02/20/funding-per-pupil-charts-for-2019/

In [22]:
# LOCAL FUNDING PER PUPIL

# Read CSV for median household income 
funding_data = pd.read_csv("https://raw.githubusercontent.com/lgmueller/lgmueller.github.io/main/Local%20Funding%20for%20Public%20Schools%20Per%20Pupil.csv")
funding_data.head()

              County  Year  Local Funding Per Pupil
0   Worcester County  2018                    13256
1  Montgomery County  2018                    10599
2      Howard County  2018                    10321
3        Kent County  2018                     9236
4      Talbot County  2018                     8621

In [23]:
# UNEMPLOYMENT RATES 

tables = pd.read_html('https://msa.maryland.gov/msa/mdmanual/01glance/economy/html/unemployrates.html#:~:text=In%20March%202022%2C%20Maryland%27s%20unemployment,civilian%20population%20number%2C%20was%2065.6') 
# Returns list of all tables on page

# Step 2: Data Management and Representation

Here we organize the data/clean it up

ADD Description of code below

In [24]:
# Cleaning up violent crime data

# only looking at years 2017, 2018, 2019
years = [2017, 2018, 2019]
# create separate dataframes for crime in 2017, 2018, and 2019
crime_17 = crime_data[crime_data.YEAR.eq(2017)]
crime_18 = crime_data[crime_data.YEAR.eq(2018)]
crime_19 = crime_data[crime_data.YEAR.eq(2019)]

# merge all three dataframes
crime_df = pd.concat([crime_17, crime_18, crime_19])

# only keep first 19 columns of the dataframe since this is the only relevant information needed
crime_df = crime_df.iloc[:, :19]

# remove the percent change and individual crime total columns since this data is not needed for our analysis
crime_df = crime_df.drop(columns = ['PERCENT CHANGE', 'VIOLENT CRIME TOTAL', 'VIOLENT CRIME PERCENT', 'VIOLENT CRIME PERCENT CHANGE', 'PROPERTY CRIME TOTALS', 'PROPERTY CRIME PERCENT', 'PROPERTY CRIME PERCENT CHANGE'])

# reset dataframe index so it starts at 0
crime_df = crime_df.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

crime_df.head()

,index,JURISDICTION,YEAR,POPULATION,MURDER,RAPE,ROBBERY,AGG. ASSAULT,B & E,LARCENY THEFT,M/V THEFT,GRAND TOTAL,"OVERALL CRIME RATE PER 100,000 PEOPLE"
0,40,Allegany County,2017,71616,4,14,58,168,469,1724,46,2483,3467.1
1,87,Anne Arundel County,2017,572990,21,172,629,1433,1729,9388,667,14039,2450.1
2,132,Baltimore City,2017,613217,342,385,5926,5874,8056,17365,5184,43132,7033.7
3,177,Baltimore County,2017,834727,35,326,1536,3166,3128,18178,2029,28398,3402.1
4,222,Calvert County,2017,91587,2,12,14,79,151,743,57,1058,1155.2

In [25]:
# MEDIAN HOUSEHOLD INCOME DATA CLEANUP

# remove all margin of error rows 
income_df = income_data[income_data['Data'] == 'Income']
income_df

# remove "Data" "MARYLAND", AND "Date Created" columns

income_df = income_df.drop(columns = ['Date created', 'Data', 'MARYLAND'])


# only keep rows for years 2017, 2018, and 2019
income_17 = income_df[income_df['Year'] == 2017]
income_18 = income_df[income_df['Year'] == 2018]
income_19 = income_df[income_df['Year'] == 2019]

# transpose data frame so county names are rows (similar to violent crime data frame) 
income_17 = income_17.T
# delete year column
income_17 = income_17.iloc[1:, :]
# rename column to income
income_17.rename(columns = {14:'Income'}, inplace = True)
# add year column 
income_17 = income_17.assign(Year='2017')[['Year'] + income_17.columns.tolist()]

# transpose data frame so county names are rows (similar to violent crime data frame) 
income_18 = income_18.T
# delete year column
income_18 = income_18.iloc[1:, :]
# rename column to income
income_18.rename(columns = {16:'Income'}, inplace = True)
# add year column 
income_18 = income_18.assign(Year='2018')[['Year'] + income_18.columns.tolist()]

# transpose data frame so county names are rows (similar to violent crime data frame) 
income_19 = income_19.T
# delete year column
income_19 = income_19.iloc[1:, :]
# rename column to income
income_19.rename(columns = {18:'Income'}, inplace = True)
# add year column 
income_19 = income_19.assign(Year='2019')[['Year'] + income_19.columns.tolist()]

# merge all three dataframes
income_df = pd.concat([income_17, income_18, income_19])
income_df.reset_index(inplace=True)
income_df.rename(columns = {'index':'County'}, inplace = True)

In [26]:
# FUNDING DATA CLEANUP

funding_data = funding_data.sort_values(by=['Year', 'County'])
funding_data.reset_index(inplace=True)
funding_df = funding_data
funding_df = funding_df.drop(columns = ['index'])

funding_df.head()

                County  Year  Local Funding Per Pupil
0      Allegany County  2018                     3714
1  Anne Arundel County  2018                     8431
2       Baltimore City  2018                     3645
3     Baltimore County  2018                     7208
4       Calvert County  2018                     7808

In [27]:
# UNEMPLOYMENT RATE DATA CLEANUP 

tables = pd.read_html('https://msa.maryland.gov/msa/mdmanual/01glance/economy/html/unemployrates.html#:~:text=In%20March%202022%2C%20Maryland%27s%20unemployment,civilian%20population%20number%2C%20was%2065.6') 
table0 = tables[0] 
table1 = tables[1]
table0.drop(columns = [2,3,4,5], inplace = True)
table0.drop(index = 0, inplace = True)
#table0 = table0.transpose()
table0
#table1 = table1.transpose()
table1.drop(index = 0, inplace = True)

unemployment1 = pd.DataFrame(columns = ["County", "Year", "UnemploymentRate"])
unemployment2 = pd.DataFrame(columns = ["County", "Year", "UnemploymentRate"])
unemployment3 = pd.DataFrame(columns = ["County", "Year", "UnemploymentRate"])
unemployment4 = pd.DataFrame(columns = ["County", "Year", "UnemploymentRate"])
unemployment5 = pd.DataFrame(columns = ["County", "Year", "UnemploymentRate"])

for row, val in table1.iterrows():
    unemployment1.loc[row, "County"] = val[0]
    unemployment1.Year = 2015
    unemployment1.loc[row, "UnemploymentRate"] = float(val[1].rstrip(val[1][-1]))

for row, val in table1.iterrows():
    unemployment2.loc[row, "County"] = val[0]
    unemployment2.Year = 2016
    unemployment2.loc[row, "UnemploymentRate"] = float(val[2].rstrip(val[2][-1]))

for row, val in table1.iterrows():
    unemployment3.loc[row, "County"] = val[0]
    unemployment3.Year = 2017
    unemployment3.loc[row, "UnemploymentRate"] = float(val[3].rstrip(val[3][-1]))
    
for row, val in table1.iterrows():
    unemployment4.loc[row, "County"] = val[0]
    unemployment4.Year = 2018
    unemployment4.loc[row, "UnemploymentRate"] = float(val[4].rstrip(val[4][-1]))
    
for row, val in table1.iterrows():
    unemployment5.loc[row, "County"] = val[0]
    unemployment5.Year = 2019
    unemployment5.loc[row, "UnemploymentRate"] = float(val[5].rstrip(val[5][-1]))
    
unemployment = pd.concat([unemployment1,unemployment2,unemployment3,unemployment4,unemployment5])
unemployment.drop(index= 1, inplace = True)
unemployment.reset_index(inplace = True)
unemployment.drop(columns = ["index"], inplace = True)

# only keep rows for years 2017, 2018, and 2019
unemploy_17 = unemployment[unemployment['Year'] == 2017]
unemploy_18 = unemployment[unemployment['Year'] == 2018]
unemploy_19 = unemployment[unemployment['Year'] == 2019]

# merge all three dataframes
unemploy_df = pd.concat([unemploy_17, unemploy_18, unemploy_19])

# drop rows with overall Maryland 
unemploy_df = unemploy_df.loc[unemploy_df['County'] != "Maryland"]

# change types of data 
unemploy_df['UnemploymentRate'] = unemploy_df['UnemploymentRate'].astype('float64')
unemploy_df = unemploy_df.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

unemploy_df.head()

   index               County  Year  UnemploymentRate
0     51      Allegany County  2017               5.7
1     52  Anne Arundel County  2017               3.5
2     53       Baltimore City  2017               6.1
3     54     Baltimore County  2017               4.3
4     55       Calvert County  2017               3.6

# Part 3: Exploratory data analysis

In [28]:
# Plot years vs overall crime rate

years = [2017, 2018, 2019]
county_names = crime_df.JURISDICTION.unique()
county_names_first_10 = county_names[0 : 9]
county_names_middle_10 = county_names[10 : 19]
print(county_names)
print(county_names_first_10)
print(county_names_middle_10)
repeat_county = ['Talbot County', 'Washington County', 'Wicomico County', 'Worcester County']

plt.figure(figsize=(20,18))
for curr_county in county_names_first_20:
    # dataframe for current county data
    curr_county_crime = crime_df[crime_df['JURISDICTION'] == curr_county]
    
    # turn data from dataframe into array to plot
    curr_years = curr_county_crime['YEAR'].to_numpy()
    curr_crime = curr_county_crime['OVERALL CRIME RATE PER 100,000 PEOPLE'].to_numpy()
    plt.title('MD Counties Crime Rate (2017-2019)')
    plt.xlabel('Years')
    plt.ylabel('Crime Rate per 100K people')
    plt.plot(curr_years, curr_crime, label = curr_county)
    
for curr_county in repeat_county:
    # dataframe for current county data
    curr_county_crime = crime_df[crime_df['JURISDICTION'] == curr_county]
    
    # turn data from dataframe into array to plot
    curr_years = curr_county_crime['YEAR'].to_numpy()
    curr_crime = curr_county_crime['OVERALL CRIME RATE PER 100,000 PEOPLE'].to_numpy()
    plt.title('MD Counties Crime Rate (2017-2019)')
    plt.xlabel('Years')
    plt.ylabel('Crime Rate per 100K people')
    plt.plot(curr_years, curr_crime, linestyle='dashed')
    
plt.legend(county_names, loc = "upper left")
plt.show()

['Allegany County' 'Anne Arundel County' 'Baltimore City'
 'Baltimore County' 'Calvert County' 'Caroline County' 'Carroll County'
 'Cecil County' 'Charles County' 'Dorchester County' 'Frederick County'
 'Garrett County' 'Harford County' 'Howard County' 'Kent County'
 'Montgomery County' "Prince George's County" "Queen Anne's County"
 'Somerset County' "St. Mary's County" 'Talbot County' 'Washington County'
 'Wicomico County' 'Worcester County']
['Allegany County' 'Anne Arundel County' 'Baltimore City'
 'Baltimore County' 'Calvert County' 'Caroline County' 'Carroll County'
 'Cecil County' 'Charles County']
['Frederick County' 'Garrett County' 'Harford County' 'Howard County'
 'Kent County' 'Montgomery County' "Prince George's County"
 "Queen Anne's County" 'Somerset County']

NameError: name 'county_names_first_20' is not defined

ADD EXPLANATION ABOUT TRENDS

In [29]:
# Plot years vs median household income

years = [2017, 2018, 2019]
county_names = income_df.County.unique()

county_names_first_20 = county_names[: -4]
#print(county_names_first_20)
repeat_county = ['Talbot County', 'Washington County', 'Wicomico County', 'Worcester County']

plt.figure(figsize=(20,18))
for curr_county in county_names_first_20:
    # dataframe for current county data
    curr_county_income = income_df[income_df['County'] == curr_county]
    
    # turn data from dataframe into array to plot
    curr_years = curr_county_income['Year'].to_numpy()
    curr_income = curr_county_income['Income'].to_numpy()
    plt.title('MD Counties Median Household Income (2017-2019)')
    plt.xlabel('Years')
    plt.ylabel('Median House Hold Income ($)')
    plt.plot(curr_years, curr_income, label = curr_county)
    
for curr_county in repeat_county:
    # dataframe for current county data
    curr_county_income = income_df[income_df['County'] == curr_county]
    
    # turn data from dataframe into array to plot
    curr_years = curr_county_income['Year'].to_numpy()
    curr_income = curr_county_income['Income'].to_numpy()
    plt.title('MD Counties Median Household Income (2017-2019)')
    plt.xlabel('Years')
    plt.ylabel('Median House Hold Income ($)')
    plt.plot(curr_years, curr_income, linestyle='dashed')
    
plt.legend(county_names, loc = "upper left")
plt.show()

In [30]:
# Combine crime and income dataframes 
crime_df['INCOME'] = income_df['Income']
# make sure rows align
crime_df['align income'] = income_df['County']==crime_df['JURISDICTION']

crime_df.info()

# Crime Rate vs Median Household Income 
EXPLANATION

In [31]:
# Get graph of crime rate vs income per year
by_year = crime_df.groupby(crime_df['YEAR'])

index = 0   # must keep track of overall index in dataframe
for year in years: 
    group = by_year.get_group(year)
    plt.figure(figsize=(20, 20))
    for i in range(index, index+len(group)):
        if (group['align income'][i]):
            plt.scatter(group['INCOME'][i], group['OVERALL CRIME RATE PER 100,000 PEOPLE'][i])
            plt.annotate(group['JURISDICTION'][i], (group['INCOME'][i], group['OVERALL CRIME RATE PER 100,000 PEOPLE'][i]))
    index = index + len(group)
    plt.xlabel('Income')
    plt.ylabel('Crime Rate')
    plt.legend(group['JURISDICTION'])
    plt.title("Income vs Crime Rate for " + str(year))
    
    # add linear regression 
    z = np.polyfit(group['INCOME'], group['OVERALL CRIME RATE PER 100,000 PEOPLE'], 1)
    linReg = np.poly1d(z)
    plt.plot(group['INCOME'], linReg(group['INCOME']), '-')
    plt.show()

Above are graphs depicting the relationship between the County's median income and its crime rate separated by year. Over the past years 2017, 2018, and 2019, one can see an overall trend. As the median household income increases, the crime rate in that county decreases.

# Crime Rate vs Local Spending 
EXPLANATION

In [32]:
# combine crime and education spending dataframes 

# since funding df only has 2018 and 2019 data, remove 2017 from crime
crime_18_19 = crime_df.loc[crime_df['YEAR'] != 2017]
crime_18_19 = crime_18_19.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

crime_18_19['FUNDING'] = funding_df['Local Funding Per Pupil']
# make sure rows align
crime_18_19['align funding'] = funding_df['County']==crime_18_19['JURISDICTION']

crime_18_19.head()

,level_0,index,JURISDICTION,YEAR,POPULATION,MURDER,RAPE,ROBBERY,AGG. ASSAULT,B & E,LARCENY THEFT,M/V THEFT,GRAND TOTAL,"OVERALL CRIME RATE PER 100,000 PEOPLE",INCOME,align income,FUNDING,align funding
0,24,41,Allegany County,2018,70577,2,20,42,189,404,1182,57,1896,2686.4,43535,True,3714,True
1,25,88,Anne Arundel County,2018,573631,25,168,473,1382,1359,8445,688,12540,2186.1,97051,True,8431,True
2,26,133,Baltimore City,2018,605436,309,367,5130,5415,6074,17102,4389,38786,6406.3,50501,True,3645,True
3,27,178,Baltimore County,2018,829560,28,352,1337,3135,2612,16882,1847,26193,3157.5,75836,True,7208,True
4,28,223,Calvert County,2018,91132,1,15,19,76,148,726,48,1033,1133.5,106270,True,7808,True

In [33]:
# Get graph of crime rate vs funding per year
by_year = crime_18_19.groupby(crime_18_19['YEAR'])

index = 0   # must keep track of overall index in dataframe
for year in [2018, 2019]: 
    group = by_year.get_group(year)
    plt.figure(figsize=(20, 20))
    for i in range(index, index+len(group)):
        if (group['align funding'][i]):
            plt.scatter(group['FUNDING'][i], group['OVERALL CRIME RATE PER 100,000 PEOPLE'][i])
            plt.annotate(group['JURISDICTION'][i], (group['FUNDING'][i], group['OVERALL CRIME RATE PER 100,000 PEOPLE'][i]))
    index = index + len(group)
    plt.xlabel('Local Funding')
    plt.ylabel('Crime Rate')
    plt.legend(group['JURISDICTION'])
    plt.title("Spending vs Crime Rate for " + str(year))
    
    # add linear regression 
    z = np.polyfit(group['FUNDING'], group['OVERALL CRIME RATE PER 100,000 PEOPLE'], 1)
    linReg = np.poly1d(z)
    plt.plot(group['FUNDING'], linReg(group['FUNDING']), '-')
    plt.show()

Above are graphs depicting the relationship between the County's local funding and its crime rate separated by year. Over the past years 2018 and 2019, one can see an overall trend. As the local spending per pupil increases, the crime rate in that county decreases.

# Crime Rate vs Unemployment  
EXPLANATION

In [34]:
# Combine crime and income dataframes 
crime_df['UNEMPLOYMENT'] = unemploy_df['UnemploymentRate']
# make sure rows align
crime_df['align employ'] = unemploy_df['County']==crime_df['JURISDICTION']

crime_df.head()

,index,JURISDICTION,YEAR,POPULATION,MURDER,RAPE,ROBBERY,AGG. ASSAULT,B & E,LARCENY THEFT,M/V THEFT,GRAND TOTAL,"OVERALL CRIME RATE PER 100,000 PEOPLE",INCOME,align income,UNEMPLOYMENT,align employ
0,40,Allegany County,2017,71616,4,14,58,168,469,1724,46,2483,3467.1,42564,True,5.7,True
1,87,Anne Arundel County,2017,572990,21,172,629,1433,1729,9388,667,14039,2450.1,96133,True,3.5,True
2,132,Baltimore City,2017,613217,342,385,5926,5874,8056,17365,5184,43132,7033.7,46762,True,6.1,True
3,177,Baltimore County,2017,834727,35,326,1536,3166,3128,18178,2029,28398,3402.1,73309,True,4.3,True
4,222,Calvert County,2017,91587,2,12,14,79,151,743,57,1058,1155.2,100000,True,3.6,True

In [35]:
by_year = crime_df.groupby(crime_df['YEAR'])

index = 0   # must keep track of overall index in dataframe
for year in years: 
    group = by_year.get_group(year)
    plt.figure(figsize=(20, 20))
    for i in range(index, index+len(group)):
        if (group['align employ'][i]):
            plt.scatter(group['UNEMPLOYMENT'][i], group['OVERALL CRIME RATE PER 100,000 PEOPLE'][i])
            plt.annotate(group['JURISDICTION'][i], (group['UNEMPLOYMENT'][i], group['OVERALL CRIME RATE PER 100,000 PEOPLE'][i]))
    index = index + len(group)
    plt.xlabel('Unemployment Rate')
    plt.ylabel('Crime Rate')
    plt.legend(group['JURISDICTION'])
    plt.title("Unemployment vs Crime Rate for " + str(year))
    
    # add linear regression 
    z = np.polyfit(group['UNEMPLOYMENT'], group['OVERALL CRIME RATE PER 100,000 PEOPLE'], 1)
    linReg = np.poly1d(z)
    plt.plot(group['UNEMPLOYMENT'], linReg(group['UNEMPLOYMENT']), '-')
    plt.show()

Above are graphs depicting the relationship between the County's unemployment and its crime rate separated by year. Over the past years 2017, 2018, and 2019, one can see an overall trend. As the unemployment rate increases, the crime rate in that county increases.

# Create Model for 2018
EXPLANATION

In [62]:
# get dataframes for only 2018 
crime_18 = crime_df.loc[crime_df['YEAR'] == 2018]
fund_18 = crime_18_19.loc[crime_18_19['YEAR'] == 2018]
crime_18 = crime_18.join(fund_18['FUNDING'])
crime_18.head()

,index,JURISDICTION,YEAR,POPULATION,MURDER,RAPE,ROBBERY,AGG. ASSAULT,B & E,LARCENY THEFT,M/V THEFT,GRAND TOTAL,"OVERALL CRIME RATE PER 100,000 PEOPLE",INCOME,align income,UNEMPLOYMENT,align employ,FUNDING
24,41,Allegany County,2018,70577,2,20,42,189,404,1182,57,1896,2686.4,43535,True,5.3,True,NaN
25,88,Anne Arundel County,2018,573631,25,168,473,1382,1359,8445,688,12540,2186.1,97051,True,3.2,True,NaN
26,133,Baltimore City,2018,605436,309,367,5130,5415,6074,17102,4389,38786,6406.3,50501,True,5.6,True,NaN
27,178,Baltimore County,2018,829560,28,352,1337,3135,2612,16882,1847,26193,3157.5,75836,True,3.9,True,NaN
28,223,Calvert County,2018,91132,1,15,19,76,148,726,48,1033,1133.5,106270,True,3.4,True,NaN

In [58]:
# create variables for model 
X = crime_18[['INCOME',
              'UNEMPLOYMENT', 
              'Local Funding Per Pupil']]
X = pd.get_dummies(data=X, drop_first=True)
Y = crime_18['OVERALL CRIME RATE PER 100,000 PEOPLE']
X.head()

    INCOME  UNEMPLOYMENT  Local Funding Per Pupil
24   43535           5.3                      NaN
25   97051           3.2                      NaN
26   50501           5.6                      NaN
27   75836           3.9                      NaN
28  106270           3.4                      NaN